### ISSUE TITLE
No Except built-in

### ISSUE THREAD

**Issue by pythoninthegrass** [rtrouton/set_microsoft_outlook_as_default_application#1]
**First**
Your Automator script did exactly what I needed! Hate having to open Mail then setup an account only to remove it after Outlook can be set as the default client. Nice job!

**Second**
Without diving into the script, it looks like there's no except clause (thinking try and except in Python) if the program's re-ran. It just has the original options to hit OK or Cancel.

Is there a way to detect if Outlook is already the default program and/or reset to the original default (i.e., Mail)? I might experiment, but AppleScript is foreign to me.

**Comment by rtrouton** [comment]
I'm glad to hear it solved your problem, and please feel free to experiment with it using what I've posted to the repo.

To the best of my knowledge, [duti](http://duti.org/) is idempotent so if Outlook was already selected as the default application, re-running this application shouldn't cause issues.
